//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystemAssets/MyInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputMap"",
    ""maps"": [
        {
            ""name"": ""VRBasic"",
            ""id"": ""496c32ea-5d66-493c-ac39-adccb76c7104"",
            ""actions"": [
                {
                    ""name"": ""LH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""c5efd29a-3159-4a8f-927c-de9f32d3f59a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""45f6beeb-c813-4dc1-ad2d-5d319eb1dfd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b75c2b18-ea4c-42c3-a2e5-6affbc3b9d74"",
                    ""path"": ""<XRController>{LeftHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b193eef6-6fb2-470d-b0b2-79df5fd75e1e"",
                    ""path"": ""<XRController>{RightHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""1807ceb7-ca96-4352-a61e-fa0bfe4da55c"",
            ""actions"": [
                {
                    ""name"": ""AnyInput"",
                    ""type"": ""Button"",
                    ""id"": ""db3a0538-95cd-43df-8cc6-46f6d42058c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""96593c8e-fdfa-4778-b0b1-bf8d774dba4f"",
                    ""path"": ""*/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ce3efbb-4817-4455-8ce6-6a05da6aa754"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Ellie"",
            ""id"": ""95447849-4482-4480-bb0c-42b0541296ed"",
            ""actions"": [
                {
                    ""name"": ""MoveA"",
                    ""type"": ""Button"",
                    ""id"": ""7d8592f6-569c-48e4-8527-7ef2d46020b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveB"",
                    ""type"": ""Button"",
                    ""id"": ""672c93b0-bd1e-40c4-b2be-d3fa6bf24d21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveC"",
                    ""type"": ""Button"",
                    ""id"": ""69b60b80-8c32-44cf-833f-57044b329750"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""ea72c66f-bd56-407e-88af-f469d310b2bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""342a951b-a2fa-46e8-a2c1-9936cf537459"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0687473-b210-4f19-94ef-ed7f176bd81d"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e84ef37-9dc7-4e02-9549-3e1284dad7ff"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8303bd2f-3016-41a1-9046-5f5e3e7f8bc5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRBasic
        m_VRBasic = asset.FindActionMap("VRBasic", throwIfNotFound: true);
        m_VRBasic_LH_TrackState = m_VRBasic.FindAction("LH_TrackState", throwIfNotFound: true);
        m_VRBasic_RH_TrackState = m_VRBasic.FindAction("RH_TrackState", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_AnyInput = m_Gameplay.FindAction("AnyInput", throwIfNotFound: true);
        // Ellie
        m_Ellie = asset.FindActionMap("Ellie", throwIfNotFound: true);
        m_Ellie_MoveA = m_Ellie.FindAction("MoveA", throwIfNotFound: true);
        m_Ellie_MoveB = m_Ellie.FindAction("MoveB", throwIfNotFound: true);
        m_Ellie_MoveC = m_Ellie.FindAction("MoveC", throwIfNotFound: true);
        m_Ellie_Reset = m_Ellie.FindAction("Reset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRBasic
    private readonly InputActionMap m_VRBasic;
    private List<IVRBasicActions> m_VRBasicActionsCallbackInterfaces = new List<IVRBasicActions>();
    private readonly InputAction m_VRBasic_LH_TrackState;
    private readonly InputAction m_VRBasic_RH_TrackState;
    public struct VRBasicActions
    {
        private @MyInputMap m_Wrapper;
        public VRBasicActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @LH_TrackState => m_Wrapper.m_VRBasic_LH_TrackState;
        public InputAction @RH_TrackState => m_Wrapper.m_VRBasic_RH_TrackState;
        public InputActionMap Get() { return m_Wrapper.m_VRBasic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRBasicActions set) { return set.Get(); }
        public void AddCallbacks(IVRBasicActions instance)
        {
            if (instance == null || m_Wrapper.m_VRBasicActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Add(instance);
            @LH_TrackState.started += instance.OnLH_TrackState;
            @LH_TrackState.performed += instance.OnLH_TrackState;
            @LH_TrackState.canceled += instance.OnLH_TrackState;
            @RH_TrackState.started += instance.OnRH_TrackState;
            @RH_TrackState.performed += instance.OnRH_TrackState;
            @RH_TrackState.canceled += instance.OnRH_TrackState;
        }

        private void UnregisterCallbacks(IVRBasicActions instance)
        {
            @LH_TrackState.started -= instance.OnLH_TrackState;
            @LH_TrackState.performed -= instance.OnLH_TrackState;
            @LH_TrackState.canceled -= instance.OnLH_TrackState;
            @RH_TrackState.started -= instance.OnRH_TrackState;
            @RH_TrackState.performed -= instance.OnRH_TrackState;
            @RH_TrackState.canceled -= instance.OnRH_TrackState;
        }

        public void RemoveCallbacks(IVRBasicActions instance)
        {
            if (m_Wrapper.m_VRBasicActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVRBasicActions instance)
        {
            foreach (var item in m_Wrapper.m_VRBasicActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VRBasicActions @VRBasic => new VRBasicActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_AnyInput;
    public struct GameplayActions
    {
        private @MyInputMap m_Wrapper;
        public GameplayActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @AnyInput => m_Wrapper.m_Gameplay_AnyInput;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @AnyInput.started += instance.OnAnyInput;
            @AnyInput.performed += instance.OnAnyInput;
            @AnyInput.canceled += instance.OnAnyInput;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @AnyInput.started -= instance.OnAnyInput;
            @AnyInput.performed -= instance.OnAnyInput;
            @AnyInput.canceled -= instance.OnAnyInput;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Ellie
    private readonly InputActionMap m_Ellie;
    private List<IEllieActions> m_EllieActionsCallbackInterfaces = new List<IEllieActions>();
    private readonly InputAction m_Ellie_MoveA;
    private readonly InputAction m_Ellie_MoveB;
    private readonly InputAction m_Ellie_MoveC;
    private readonly InputAction m_Ellie_Reset;
    public struct EllieActions
    {
        private @MyInputMap m_Wrapper;
        public EllieActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveA => m_Wrapper.m_Ellie_MoveA;
        public InputAction @MoveB => m_Wrapper.m_Ellie_MoveB;
        public InputAction @MoveC => m_Wrapper.m_Ellie_MoveC;
        public InputAction @Reset => m_Wrapper.m_Ellie_Reset;
        public InputActionMap Get() { return m_Wrapper.m_Ellie; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EllieActions set) { return set.Get(); }
        public void AddCallbacks(IEllieActions instance)
        {
            if (instance == null || m_Wrapper.m_EllieActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EllieActionsCallbackInterfaces.Add(instance);
            @MoveA.started += instance.OnMoveA;
            @MoveA.performed += instance.OnMoveA;
            @MoveA.canceled += instance.OnMoveA;
            @MoveB.started += instance.OnMoveB;
            @MoveB.performed += instance.OnMoveB;
            @MoveB.canceled += instance.OnMoveB;
            @MoveC.started += instance.OnMoveC;
            @MoveC.performed += instance.OnMoveC;
            @MoveC.canceled += instance.OnMoveC;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
        }

        private void UnregisterCallbacks(IEllieActions instance)
        {
            @MoveA.started -= instance.OnMoveA;
            @MoveA.performed -= instance.OnMoveA;
            @MoveA.canceled -= instance.OnMoveA;
            @MoveB.started -= instance.OnMoveB;
            @MoveB.performed -= instance.OnMoveB;
            @MoveB.canceled -= instance.OnMoveB;
            @MoveC.started -= instance.OnMoveC;
            @MoveC.performed -= instance.OnMoveC;
            @MoveC.canceled -= instance.OnMoveC;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
        }

        public void RemoveCallbacks(IEllieActions instance)
        {
            if (m_Wrapper.m_EllieActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEllieActions instance)
        {
            foreach (var item in m_Wrapper.m_EllieActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EllieActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EllieActions @Ellie => new EllieActions(this);
    public interface IVRBasicActions
    {
        void OnLH_TrackState(InputAction.CallbackContext context);
        void OnRH_TrackState(InputAction.CallbackContext context);
    }
    public interface IGameplayActions
    {
        void OnAnyInput(InputAction.CallbackContext context);
    }
    public interface IEllieActions
    {
        void OnMoveA(InputAction.CallbackContext context);
        void OnMoveB(InputAction.CallbackContext context);
        void OnMoveC(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
    }
}
