//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystemAssets/MyInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputMap"",
    ""maps"": [
        {
            ""name"": ""VRBasic"",
            ""id"": ""496c32ea-5d66-493c-ac39-adccb76c7104"",
            ""actions"": [
                {
                    ""name"": ""LH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""c5efd29a-3159-4a8f-927c-de9f32d3f59a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""45f6beeb-c813-4dc1-ad2d-5d319eb1dfd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b75c2b18-ea4c-42c3-a2e5-6affbc3b9d74"",
                    ""path"": ""<XRController>{LeftHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b193eef6-6fb2-470d-b0b2-79df5fd75e1e"",
                    ""path"": ""<XRController>{RightHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""2f8dad00-5b92-49a4-9bbd-3250bbce818c"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""07735936-7d24-4304-8b15-5cf43e9a550b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AnyInput"",
                    ""type"": ""Button"",
                    ""id"": ""02a718b8-83df-4252-8416-bf2ca13008cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa6eb0c5-2c78-4c89-8357-c82309962acb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc2f27ff-1342-431c-a13a-c5ffa49dce2b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Ellie"",
            ""id"": ""119323de-738d-4e6c-9c98-3e210b795655"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""13ddecf5-337d-4abe-a9fd-24b625f8c0e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBG"",
                    ""type"": ""Button"",
                    ""id"": ""31c82216-671f-4e4a-acd1-abcdff2783df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AnyInput"",
                    ""type"": ""Button"",
                    ""id"": ""90c1292e-5d3c-4499-ad6a-f8b7d748dd40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchMove"",
                    ""type"": ""Button"",
                    ""id"": ""350b3d0a-1e91-4165-963b-119610ebb81f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveA"",
                    ""type"": ""Button"",
                    ""id"": ""40046028-0cd8-4322-9d5f-96fbdd6bc5e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveB"",
                    ""type"": ""Button"",
                    ""id"": ""de9c6922-4163-4e92-a02e-4ccb27b06903"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveC"",
                    ""type"": ""Button"",
                    ""id"": ""6dce0035-431d-442d-9414-ae9a59a6bf33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""03ca2843-d490-4511-a7dd-b5bfbcab390d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""392f77fc-c6a8-4916-92a5-2d47c4b8547f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d9164a2-a202-4e3c-9f03-c4611d997d6a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2dd30bc-e991-4406-b5ff-7ceb68f1c91d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3fe5327-822f-4c21-be7b-375684f04582"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93c2a7a9-f33b-45da-8935-e10fc4dca712"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0949721-f0a4-4323-a218-98d0683d8f7e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""874eeb3a-b565-484a-b5f6-60f1855153fc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8ef9c5e-8b73-40f7-9283-10203b8b525a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRBasic
        m_VRBasic = asset.FindActionMap("VRBasic", throwIfNotFound: true);
        m_VRBasic_LH_TrackState = m_VRBasic.FindAction("LH_TrackState", throwIfNotFound: true);
        m_VRBasic_RH_TrackState = m_VRBasic.FindAction("RH_TrackState", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Newaction = m_Gameplay.FindAction("New action", throwIfNotFound: true);
        m_Gameplay_AnyInput = m_Gameplay.FindAction("AnyInput", throwIfNotFound: true);
        // Ellie
        m_Ellie = asset.FindActionMap("Ellie", throwIfNotFound: true);
        m_Ellie_Newaction = m_Ellie.FindAction("New action", throwIfNotFound: true);
        m_Ellie_SwitchBG = m_Ellie.FindAction("SwitchBG", throwIfNotFound: true);
        m_Ellie_AnyInput = m_Ellie.FindAction("AnyInput", throwIfNotFound: true);
        m_Ellie_SwitchMove = m_Ellie.FindAction("SwitchMove", throwIfNotFound: true);
        m_Ellie_MoveA = m_Ellie.FindAction("MoveA", throwIfNotFound: true);
        m_Ellie_MoveB = m_Ellie.FindAction("MoveB", throwIfNotFound: true);
        m_Ellie_MoveC = m_Ellie.FindAction("MoveC", throwIfNotFound: true);
        m_Ellie_Reset = m_Ellie.FindAction("Reset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRBasic
    private readonly InputActionMap m_VRBasic;
    private List<IVRBasicActions> m_VRBasicActionsCallbackInterfaces = new List<IVRBasicActions>();
    private readonly InputAction m_VRBasic_LH_TrackState;
    private readonly InputAction m_VRBasic_RH_TrackState;
    public struct VRBasicActions
    {
        private @MyInputMap m_Wrapper;
        public VRBasicActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @LH_TrackState => m_Wrapper.m_VRBasic_LH_TrackState;
        public InputAction @RH_TrackState => m_Wrapper.m_VRBasic_RH_TrackState;
        public InputActionMap Get() { return m_Wrapper.m_VRBasic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRBasicActions set) { return set.Get(); }
        public void AddCallbacks(IVRBasicActions instance)
        {
            if (instance == null || m_Wrapper.m_VRBasicActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Add(instance);
            @LH_TrackState.started += instance.OnLH_TrackState;
            @LH_TrackState.performed += instance.OnLH_TrackState;
            @LH_TrackState.canceled += instance.OnLH_TrackState;
            @RH_TrackState.started += instance.OnRH_TrackState;
            @RH_TrackState.performed += instance.OnRH_TrackState;
            @RH_TrackState.canceled += instance.OnRH_TrackState;
        }

        private void UnregisterCallbacks(IVRBasicActions instance)
        {
            @LH_TrackState.started -= instance.OnLH_TrackState;
            @LH_TrackState.performed -= instance.OnLH_TrackState;
            @LH_TrackState.canceled -= instance.OnLH_TrackState;
            @RH_TrackState.started -= instance.OnRH_TrackState;
            @RH_TrackState.performed -= instance.OnRH_TrackState;
            @RH_TrackState.canceled -= instance.OnRH_TrackState;
        }

        public void RemoveCallbacks(IVRBasicActions instance)
        {
            if (m_Wrapper.m_VRBasicActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVRBasicActions instance)
        {
            foreach (var item in m_Wrapper.m_VRBasicActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VRBasicActions @VRBasic => new VRBasicActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Newaction;
    private readonly InputAction m_Gameplay_AnyInput;
    public struct GameplayActions
    {
        private @MyInputMap m_Wrapper;
        public GameplayActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Gameplay_Newaction;
        public InputAction @AnyInput => m_Wrapper.m_Gameplay_AnyInput;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
            @AnyInput.started += instance.OnAnyInput;
            @AnyInput.performed += instance.OnAnyInput;
            @AnyInput.canceled += instance.OnAnyInput;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
            @AnyInput.started -= instance.OnAnyInput;
            @AnyInput.performed -= instance.OnAnyInput;
            @AnyInput.canceled -= instance.OnAnyInput;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Ellie
    private readonly InputActionMap m_Ellie;
    private List<IEllieActions> m_EllieActionsCallbackInterfaces = new List<IEllieActions>();
    private readonly InputAction m_Ellie_Newaction;
    private readonly InputAction m_Ellie_SwitchBG;
    private readonly InputAction m_Ellie_AnyInput;
    private readonly InputAction m_Ellie_SwitchMove;
    private readonly InputAction m_Ellie_MoveA;
    private readonly InputAction m_Ellie_MoveB;
    private readonly InputAction m_Ellie_MoveC;
    private readonly InputAction m_Ellie_Reset;
    public struct EllieActions
    {
        private @MyInputMap m_Wrapper;
        public EllieActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Ellie_Newaction;
        public InputAction @SwitchBG => m_Wrapper.m_Ellie_SwitchBG;
        public InputAction @AnyInput => m_Wrapper.m_Ellie_AnyInput;
        public InputAction @SwitchMove => m_Wrapper.m_Ellie_SwitchMove;
        public InputAction @MoveA => m_Wrapper.m_Ellie_MoveA;
        public InputAction @MoveB => m_Wrapper.m_Ellie_MoveB;
        public InputAction @MoveC => m_Wrapper.m_Ellie_MoveC;
        public InputAction @Reset => m_Wrapper.m_Ellie_Reset;
        public InputActionMap Get() { return m_Wrapper.m_Ellie; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EllieActions set) { return set.Get(); }
        public void AddCallbacks(IEllieActions instance)
        {
            if (instance == null || m_Wrapper.m_EllieActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EllieActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
            @SwitchBG.started += instance.OnSwitchBG;
            @SwitchBG.performed += instance.OnSwitchBG;
            @SwitchBG.canceled += instance.OnSwitchBG;
            @AnyInput.started += instance.OnAnyInput;
            @AnyInput.performed += instance.OnAnyInput;
            @AnyInput.canceled += instance.OnAnyInput;
            @SwitchMove.started += instance.OnSwitchMove;
            @SwitchMove.performed += instance.OnSwitchMove;
            @SwitchMove.canceled += instance.OnSwitchMove;
            @MoveA.started += instance.OnMoveA;
            @MoveA.performed += instance.OnMoveA;
            @MoveA.canceled += instance.OnMoveA;
            @MoveB.started += instance.OnMoveB;
            @MoveB.performed += instance.OnMoveB;
            @MoveB.canceled += instance.OnMoveB;
            @MoveC.started += instance.OnMoveC;
            @MoveC.performed += instance.OnMoveC;
            @MoveC.canceled += instance.OnMoveC;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
        }

        private void UnregisterCallbacks(IEllieActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
            @SwitchBG.started -= instance.OnSwitchBG;
            @SwitchBG.performed -= instance.OnSwitchBG;
            @SwitchBG.canceled -= instance.OnSwitchBG;
            @AnyInput.started -= instance.OnAnyInput;
            @AnyInput.performed -= instance.OnAnyInput;
            @AnyInput.canceled -= instance.OnAnyInput;
            @SwitchMove.started -= instance.OnSwitchMove;
            @SwitchMove.performed -= instance.OnSwitchMove;
            @SwitchMove.canceled -= instance.OnSwitchMove;
            @MoveA.started -= instance.OnMoveA;
            @MoveA.performed -= instance.OnMoveA;
            @MoveA.canceled -= instance.OnMoveA;
            @MoveB.started -= instance.OnMoveB;
            @MoveB.performed -= instance.OnMoveB;
            @MoveB.canceled -= instance.OnMoveB;
            @MoveC.started -= instance.OnMoveC;
            @MoveC.performed -= instance.OnMoveC;
            @MoveC.canceled -= instance.OnMoveC;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
        }

        public void RemoveCallbacks(IEllieActions instance)
        {
            if (m_Wrapper.m_EllieActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEllieActions instance)
        {
            foreach (var item in m_Wrapper.m_EllieActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EllieActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EllieActions @Ellie => new EllieActions(this);
    public interface IVRBasicActions
    {
        void OnLH_TrackState(InputAction.CallbackContext context);
        void OnRH_TrackState(InputAction.CallbackContext context);
    }
    public interface IGameplayActions
    {
        void OnNewaction(InputAction.CallbackContext context);
        void OnAnyInput(InputAction.CallbackContext context);
    }
    public interface IEllieActions
    {
        void OnNewaction(InputAction.CallbackContext context);
        void OnSwitchBG(InputAction.CallbackContext context);
        void OnAnyInput(InputAction.CallbackContext context);
        void OnSwitchMove(InputAction.CallbackContext context);
        void OnMoveA(InputAction.CallbackContext context);
        void OnMoveB(InputAction.CallbackContext context);
        void OnMoveC(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
    }
}
