//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystemAssets/MyInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputMap"",
    ""maps"": [
        {
            ""name"": ""VRBasic"",
            ""id"": ""496c32ea-5d66-493c-ac39-adccb76c7104"",
            ""actions"": [
                {
                    ""name"": ""LH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""c5efd29a-3159-4a8f-927c-de9f32d3f59a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RH_TrackState"",
                    ""type"": ""Button"",
                    ""id"": ""45f6beeb-c813-4dc1-ad2d-5d319eb1dfd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b75c2b18-ea4c-42c3-a2e5-6affbc3b9d74"",
                    ""path"": ""<XRController>{LeftHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b193eef6-6fb2-470d-b0b2-79df5fd75e1e"",
                    ""path"": ""<XRController>{RightHand}/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RH_TrackState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRBasic
        m_VRBasic = asset.FindActionMap("VRBasic", throwIfNotFound: true);
        m_VRBasic_LH_TrackState = m_VRBasic.FindAction("LH_TrackState", throwIfNotFound: true);
        m_VRBasic_RH_TrackState = m_VRBasic.FindAction("RH_TrackState", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRBasic
    private readonly InputActionMap m_VRBasic;
    private List<IVRBasicActions> m_VRBasicActionsCallbackInterfaces = new List<IVRBasicActions>();
    private readonly InputAction m_VRBasic_LH_TrackState;
    private readonly InputAction m_VRBasic_RH_TrackState;
    public struct VRBasicActions
    {
        private @MyInputMap m_Wrapper;
        public VRBasicActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @LH_TrackState => m_Wrapper.m_VRBasic_LH_TrackState;
        public InputAction @RH_TrackState => m_Wrapper.m_VRBasic_RH_TrackState;
        public InputActionMap Get() { return m_Wrapper.m_VRBasic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRBasicActions set) { return set.Get(); }
        public void AddCallbacks(IVRBasicActions instance)
        {
            if (instance == null || m_Wrapper.m_VRBasicActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Add(instance);
            @LH_TrackState.started += instance.OnLH_TrackState;
            @LH_TrackState.performed += instance.OnLH_TrackState;
            @LH_TrackState.canceled += instance.OnLH_TrackState;
            @RH_TrackState.started += instance.OnRH_TrackState;
            @RH_TrackState.performed += instance.OnRH_TrackState;
            @RH_TrackState.canceled += instance.OnRH_TrackState;
        }

        private void UnregisterCallbacks(IVRBasicActions instance)
        {
            @LH_TrackState.started -= instance.OnLH_TrackState;
            @LH_TrackState.performed -= instance.OnLH_TrackState;
            @LH_TrackState.canceled -= instance.OnLH_TrackState;
            @RH_TrackState.started -= instance.OnRH_TrackState;
            @RH_TrackState.performed -= instance.OnRH_TrackState;
            @RH_TrackState.canceled -= instance.OnRH_TrackState;
        }

        public void RemoveCallbacks(IVRBasicActions instance)
        {
            if (m_Wrapper.m_VRBasicActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVRBasicActions instance)
        {
            foreach (var item in m_Wrapper.m_VRBasicActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VRBasicActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VRBasicActions @VRBasic => new VRBasicActions(this);
    public interface IVRBasicActions
    {
        void OnLH_TrackState(InputAction.CallbackContext context);
        void OnRH_TrackState(InputAction.CallbackContext context);
    }
}
