//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/JC_Express/NewInputSystem_Template/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""5817de3f-064b-4d9e-8120-cc5ccfb40ddf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""46884a52-6acb-4025-b136-a743d0a4b760"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NextPage"",
                    ""type"": ""Button"",
                    ""id"": ""f519e6ba-1205-4db5-b950-84412c3b820b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousPage"",
                    ""type"": ""Button"",
                    ""id"": ""4e4b2dff-a3ef-405e-b97c-ab4cfccaac7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c95b4513-e61b-4bdd-937e-0e6d0de3215a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1135c4ad-23af-4826-b715-ce0c9be0ceeb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a725d732-b761-48a9-97f3-377ff2303eb7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43021451-ba3f-40d4-9e7c-955c81219411"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""104a37da-bf59-4fdf-80a9-59b6bd491b3b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""011df923-dd60-4379-a37f-5454103817f0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3244dcf3-f81d-4d23-99b7-bfc8cd3b235c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Petroller"",
            ""id"": ""a4a41900-a733-48cd-8889-72838548932a"",
            ""actions"": [
                {
                    ""name"": ""Pull"",
                    ""type"": ""Value"",
                    ""id"": ""d0da2ba3-b422-4ad2-882d-c9b8146b0e93"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalPress"",
                    ""type"": ""Button"",
                    ""id"": ""161fdf33-2889-49b6-882a-26226d5bf8a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorizontalPress"",
                    ""type"": ""Button"",
                    ""id"": ""95f10703-6eaf-4a08-ad7a-90761a6e75a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""198cd316-34bf-4e03-a086-05e61718ac70"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""Value"",
                    ""id"": ""25085b45-5e54-4598-8278-bce7941a7e78"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""90eacbe6-65a4-44a0-8c19-45864f0e8923"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAngularVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""fc7fe55f-386d-4bda-81ed-8637ed9b5f71"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""237bbc40-d2e9-4b3d-9a6a-b5790bfc081a"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAugularAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""5ef3ca71-6b5f-4775-b32c-276b0a1ee6e6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2eafe30b-94b4-4976-9293-296f3f503351"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7c72fd-bfc1-43c3-9db1-3d9105d55c88"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a709e6f-4b32-4453-a9a7-a92d3b9e5586"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e3d842-02f7-40c6-af9a-7310c0ca9ca8"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5a37f9-97d1-4f63-9c64-70693083a955"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f44ea030-83a8-4346-800b-9a12a1b25eb6"",
                    ""path"": ""<XRController>{RightHand}/deviceVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4274467f-1163-4801-bea9-808651b504d7"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAngularVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4450fd98-01b6-428d-bfe9-a3111a408c60"",
                    ""path"": ""<XRController>{RightHand}/deviceAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ab0b91a-30ea-445f-8d1d-c0c926cc89f1"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAugularAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Prototype"",
            ""id"": ""ff4988e7-0fe6-42e9-9ea3-e4ae634bb2f7"",
            ""actions"": [
                {
                    ""name"": ""RecordButton"",
                    ""type"": ""Button"",
                    ""id"": ""80f99edc-9090-48c0-9fd6-d0303e47be54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5609f638-182e-443a-b135-17972a8834d3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Move = m_PlayerInput.FindAction("Move", throwIfNotFound: true);
        m_PlayerInput_NextPage = m_PlayerInput.FindAction("NextPage", throwIfNotFound: true);
        m_PlayerInput_PreviousPage = m_PlayerInput.FindAction("PreviousPage", throwIfNotFound: true);
        // Petroller
        m_Petroller = asset.FindActionMap("Petroller", throwIfNotFound: true);
        m_Petroller_Pull = m_Petroller.FindAction("Pull", throwIfNotFound: true);
        m_Petroller_VerticalPress = m_Petroller.FindAction("VerticalPress", throwIfNotFound: true);
        m_Petroller_HorizontalPress = m_Petroller.FindAction("HorizontalPress", throwIfNotFound: true);
        m_Petroller_Pos = m_Petroller.FindAction("Pos", throwIfNotFound: true);
        m_Petroller_Rot = m_Petroller.FindAction("Rot", throwIfNotFound: true);
        m_Petroller_DeviceVelocity = m_Petroller.FindAction("DeviceVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAngularVelocity = m_Petroller.FindAction("DeviceAngularVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAcceleration = m_Petroller.FindAction("DeviceAcceleration", throwIfNotFound: true);
        m_Petroller_DeviceAugularAcceleration = m_Petroller.FindAction("DeviceAugularAcceleration", throwIfNotFound: true);
        // Prototype
        m_Prototype = asset.FindActionMap("Prototype", throwIfNotFound: true);
        m_Prototype_RecordButton = m_Prototype.FindAction("RecordButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Move;
    private readonly InputAction m_PlayerInput_NextPage;
    private readonly InputAction m_PlayerInput_PreviousPage;
    public struct PlayerInputActions
    {
        private @ControlMap m_Wrapper;
        public PlayerInputActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerInput_Move;
        public InputAction @NextPage => m_Wrapper.m_PlayerInput_NextPage;
        public InputAction @PreviousPage => m_Wrapper.m_PlayerInput_PreviousPage;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @NextPage.started += instance.OnNextPage;
            @NextPage.performed += instance.OnNextPage;
            @NextPage.canceled += instance.OnNextPage;
            @PreviousPage.started += instance.OnPreviousPage;
            @PreviousPage.performed += instance.OnPreviousPage;
            @PreviousPage.canceled += instance.OnPreviousPage;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @NextPage.started -= instance.OnNextPage;
            @NextPage.performed -= instance.OnNextPage;
            @NextPage.canceled -= instance.OnNextPage;
            @PreviousPage.started -= instance.OnPreviousPage;
            @PreviousPage.performed -= instance.OnPreviousPage;
            @PreviousPage.canceled -= instance.OnPreviousPage;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);

    // Petroller
    private readonly InputActionMap m_Petroller;
    private List<IPetrollerActions> m_PetrollerActionsCallbackInterfaces = new List<IPetrollerActions>();
    private readonly InputAction m_Petroller_Pull;
    private readonly InputAction m_Petroller_VerticalPress;
    private readonly InputAction m_Petroller_HorizontalPress;
    private readonly InputAction m_Petroller_Pos;
    private readonly InputAction m_Petroller_Rot;
    private readonly InputAction m_Petroller_DeviceVelocity;
    private readonly InputAction m_Petroller_DeviceAngularVelocity;
    private readonly InputAction m_Petroller_DeviceAcceleration;
    private readonly InputAction m_Petroller_DeviceAugularAcceleration;
    public struct PetrollerActions
    {
        private @ControlMap m_Wrapper;
        public PetrollerActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pull => m_Wrapper.m_Petroller_Pull;
        public InputAction @VerticalPress => m_Wrapper.m_Petroller_VerticalPress;
        public InputAction @HorizontalPress => m_Wrapper.m_Petroller_HorizontalPress;
        public InputAction @Pos => m_Wrapper.m_Petroller_Pos;
        public InputAction @Rot => m_Wrapper.m_Petroller_Rot;
        public InputAction @DeviceVelocity => m_Wrapper.m_Petroller_DeviceVelocity;
        public InputAction @DeviceAngularVelocity => m_Wrapper.m_Petroller_DeviceAngularVelocity;
        public InputAction @DeviceAcceleration => m_Wrapper.m_Petroller_DeviceAcceleration;
        public InputAction @DeviceAugularAcceleration => m_Wrapper.m_Petroller_DeviceAugularAcceleration;
        public InputActionMap Get() { return m_Wrapper.m_Petroller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PetrollerActions set) { return set.Get(); }
        public void AddCallbacks(IPetrollerActions instance)
        {
            if (instance == null || m_Wrapper.m_PetrollerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Add(instance);
            @Pull.started += instance.OnPull;
            @Pull.performed += instance.OnPull;
            @Pull.canceled += instance.OnPull;
            @VerticalPress.started += instance.OnVerticalPress;
            @VerticalPress.performed += instance.OnVerticalPress;
            @VerticalPress.canceled += instance.OnVerticalPress;
            @HorizontalPress.started += instance.OnHorizontalPress;
            @HorizontalPress.performed += instance.OnHorizontalPress;
            @HorizontalPress.canceled += instance.OnHorizontalPress;
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @DeviceVelocity.started += instance.OnDeviceVelocity;
            @DeviceVelocity.performed += instance.OnDeviceVelocity;
            @DeviceVelocity.canceled += instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled += instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started += instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed += instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled += instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled += instance.OnDeviceAugularAcceleration;
        }

        private void UnregisterCallbacks(IPetrollerActions instance)
        {
            @Pull.started -= instance.OnPull;
            @Pull.performed -= instance.OnPull;
            @Pull.canceled -= instance.OnPull;
            @VerticalPress.started -= instance.OnVerticalPress;
            @VerticalPress.performed -= instance.OnVerticalPress;
            @VerticalPress.canceled -= instance.OnVerticalPress;
            @HorizontalPress.started -= instance.OnHorizontalPress;
            @HorizontalPress.performed -= instance.OnHorizontalPress;
            @HorizontalPress.canceled -= instance.OnHorizontalPress;
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @DeviceVelocity.started -= instance.OnDeviceVelocity;
            @DeviceVelocity.performed -= instance.OnDeviceVelocity;
            @DeviceVelocity.canceled -= instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled -= instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled -= instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled -= instance.OnDeviceAugularAcceleration;
        }

        public void RemoveCallbacks(IPetrollerActions instance)
        {
            if (m_Wrapper.m_PetrollerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPetrollerActions instance)
        {
            foreach (var item in m_Wrapper.m_PetrollerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PetrollerActions @Petroller => new PetrollerActions(this);

    // Prototype
    private readonly InputActionMap m_Prototype;
    private List<IPrototypeActions> m_PrototypeActionsCallbackInterfaces = new List<IPrototypeActions>();
    private readonly InputAction m_Prototype_RecordButton;
    public struct PrototypeActions
    {
        private @ControlMap m_Wrapper;
        public PrototypeActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @RecordButton => m_Wrapper.m_Prototype_RecordButton;
        public InputActionMap Get() { return m_Wrapper.m_Prototype; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrototypeActions set) { return set.Get(); }
        public void AddCallbacks(IPrototypeActions instance)
        {
            if (instance == null || m_Wrapper.m_PrototypeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Add(instance);
            @RecordButton.started += instance.OnRecordButton;
            @RecordButton.performed += instance.OnRecordButton;
            @RecordButton.canceled += instance.OnRecordButton;
        }

        private void UnregisterCallbacks(IPrototypeActions instance)
        {
            @RecordButton.started -= instance.OnRecordButton;
            @RecordButton.performed -= instance.OnRecordButton;
            @RecordButton.canceled -= instance.OnRecordButton;
        }

        public void RemoveCallbacks(IPrototypeActions instance)
        {
            if (m_Wrapper.m_PrototypeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPrototypeActions instance)
        {
            foreach (var item in m_Wrapper.m_PrototypeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PrototypeActions @Prototype => new PrototypeActions(this);
    public interface IPlayerInputActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnNextPage(InputAction.CallbackContext context);
        void OnPreviousPage(InputAction.CallbackContext context);
    }
    public interface IPetrollerActions
    {
        void OnPull(InputAction.CallbackContext context);
        void OnVerticalPress(InputAction.CallbackContext context);
        void OnHorizontalPress(InputAction.CallbackContext context);
        void OnPos(InputAction.CallbackContext context);
        void OnRot(InputAction.CallbackContext context);
        void OnDeviceVelocity(InputAction.CallbackContext context);
        void OnDeviceAngularVelocity(InputAction.CallbackContext context);
        void OnDeviceAcceleration(InputAction.CallbackContext context);
        void OnDeviceAugularAcceleration(InputAction.CallbackContext context);
    }
    public interface IPrototypeActions
    {
        void OnRecordButton(InputAction.CallbackContext context);
    }
}
